config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :restaurants, only: %i[index new show create] do
    collection do
      get :top
    end

    member do # esses que tem id
      get :chef
    end

    resources :reviews, only: %i[new create]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/restaurant.rb
class Restaurant < ApplicationRecord
  has_many :reviews, dependent: :destroy

  validates :name, presence: true
  validates :address, presence: true
  validates :phone_number, presence: true
  validates :category, presence: true
  validates :category, inclusion: %w[chinese italian japanese french belgian]
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :restaurant

  validates :content, presence: true
  validates :rating, presence: true
  validates :rating, numericality: { greater_than_or_equal_to: 0 }
  validates :rating, numericality: { less_than_or_equal_to: 5 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController
  before_action :find_restaurant, only: %i[chef show]

  def index
    @restaurants = Restaurant.all
  end

  def show; end

  def new
    @restaurant = Restaurant.new
  end

  def chef
    @chef_name = @restaurant.chef_name
  end

  def create
    @restaurant = Restaurant.new(restaurant_params)
    if @restaurant.save
      redirect_to restaurant_path(@restaurant)
    else
      render :new
    end
  end

  def top
    @restaurants = Restaurant.where(stars: 5)
  end

  private

  def restaurant_params
    params.require(:restaurant).permit(:name, :address, :phone_number, :category)
  end

  def find_restaurant
    @restaurant = Restaurant.find(params[:id])
  end
end

# validates :name, presence: true
# validates :address, presence: true
# validates :phone_number, presence: true
# validates :category, presence: true
# validates :category, inclusion: %w[chinese italian japanese french belgian]

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_action :set_restaurant, except: [:destroy]

  def new
    @review = Review.new
    # @restaurant = Restaurant.find(params[:restaurant_id])
  end

  def create
    @review = Review.new(review_params)
    # @restaurant = Restaurant.find(params[:restaurant_id])
    @review.restaurant = @restaurant

    if @review.save
      redirect_to restaurant_path(@restaurant)
    else
      render :new
    end
  end

  def destroy
    @review = Review.find(params[:id])
    @review.destroy
    redirect_to restaurant_path(@review.restaurant)
  end

  private

  def set_restaurant
    @restaurant = Restaurant.find(params[:restaurant_id])
  end

  def review_params
    params.require(:review).permit(:content, :rating)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsYelpMvp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    
    <!-- Add these line for detecting device width -->
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/restaurants/_form.html.erb
<div class="container">

  <%= simple_form_for(@restaurant) do |f| %>
    <%= f.input :name %>
    <%= f.input :address %>
    <%= f.input :phone_number %>
    <%= f.input :category, :collection => %w[chinese italian japanese french belgian] %>
    <%= f.submit %>
  <% end %>

</div>

app/views/restaurants/edit.html.erb
<%= render 'form'%>

app/views/restaurants/index.html.erb
<% @restaurants.each do |rest| %>
  <div class="card">
    <h2><%= link_to rest.name, restaurant_path(rest) %></h2>
    <p><%= rest.address %></p>
    <p><%= rest.phone_number %></p>
    <p><%= rest.category %></p>
  </div>
<% end %>

app/views/restaurants/new.html.erb
<%= render 'form'%>

app/views/restaurants/show.html.erb
<div class="container text-center">
  <div class="d-flex justify-content-around align-items-center">
    <h1> <%= @restaurant.name %> </h1>  
  </div>
  <p>  <%= @restaurant.address %>  </p>
  <br>
  <% @restaurant.reviews.each do |review| %>
  <p> <%= review.content %> </p>
  <% end %>
  <%= link_to "review", new_restaurant_review_path(@restaurant.id) %>

</div>

<%#     <%= link_to "EDIT", edit_restaurant_path %>
    <%# <%= link_to "DELETE", article_path(@restaurant), method: :delete, data:{ confirm: "Tem certeza?"} %> 

app/views/reviews/_form.html.erb
<div class="container">

  <%= simple_form_for [@restaurant, @review] do |f| %>
    <%= f.input :content %>
    <%= f.input :rating %>
    <%= f.submit %>
  <% end %>

</div>

app/views/reviews/new.html.erb
<%= render 'form'%>